AllCops:
  DisplayCopNames: true

require: rubocop-rspec

Metrics/LineLength:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false
