language: ruby
bundler_args: --without development
script: bundle exec rspec --tag ~platform:win32
rvm:
  - 2.0.0
  - 2.1.0
notifications:
  on_success: never
  recipients:
    - agross@therightstuff.de
