# Use the new container-based Travis infrastructure.
sudo: false

language: ruby
cache:
  - bundler
before_install:
  - gem install bundler --version 1.17.3
bundler_args: --without development
script:
  - bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
  - bundle exec rake package
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      os: osx

notifications:
  email:
    on_success: never

addons:
  code_climate:
    repo_token: d8b15ab15f45f543f1ddd59b4224f83e6fcc9576f2fa4ba2817ae20d445f5f4f
