deployment:
  connection:
    computer_name: localhost
    username:  <%= ENV['DEPLOY_USER'] %>
    password: <%= ENV['DEPLOY_PASSWORD'] %>
  remote_dir: <%= (File.expand_path(ENV['TEMP'] || '', '_gems')) %>
